#!/bin/bash
#
#*************************************************************************************************
#
# 88                                                                                88
# 88                                                                                ""
# 88
# 88,dPPPba,   ,adPPPba, 8b,     ,d8 ,adPPPPba,  ,adPPPb,d8  ,adPPPba,  8b,dPPPba,  88 8b,     ,d8
# 88P'    "88 a8P     88  `P8, ,8P'  ""     `P8 a8"    `P88 a8"     "8a 88P'   `"88 88  `P8, ,8P'
# 88       88 8PP"""""""    )888(    ,adPPPPP88 8b       88 8b       d8 88       88 88    )888(
# 88       88 "8b,   ,aa  ,d8" "8b,  88,    ,88 "8a,   ,d88 "8a,   ,a8" 88       88 88  ,d8" "8b,
# 88       88  `"Pbbd8"' 8P'     `P8 `"8bbdP"P8  `"PbbdP"P8  `"PbbdP"'  88       88 88 8P'     `P8
#                                               aa,    ,88
#                                                "P8bbdP"
#
#                    Sistema Operacional Hexagonix - Hexagonix Operating System
#
#                         Copyright (c) 2015-2025 Felipe Miguel Nery Lunkes
#                        Todos os direitos reservados - All rights reserved.
#
#*************************************************************************************************
#
# Português:
#
# O Hexagonix e seus componentes são licenciados sob licença BSD-3-Clause. Leia abaixo
# a licença que governa este arquivo e verifique a licença de cada repositório para
# obter mais informações sobre seus direitos e obrigações ao utilizar e reutilizar
# o código deste ou de outros arquivos.
#
# English:
#
# Hexagonix and its components are licensed under a BSD-3-Clause license. Read below
# the license that governs this file and check each repository's license for
# obtain more information about your rights and obligations when using and reusing
# the code of this or other files.
#
#*************************************************************************************************
#
# BSD 3-Clause License
#
# Copyright (c) 2015-2025, Felipe Miguel Nery Lunkes
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# $HexagonixOS$

function main() {

systemBuilder

}

function systemBuilder() {

echo -e "Starting Hexagonix system builder mod version $MOD_VER...\n" >> $LOG

export MSG="Building the Hexagonix"

clear

callHXMod common banner

echo "Building the Hexagonix..."
echo

mkdir -p $BUILD_DIRECTORY
mkdir -p $BUILD_DIRECTORY/bin
mkdir -p $BUILD_DIRECTORY/etc

callHXMod saturno
callHXMod hboot
callHXMod hexagon
callHXMod unix
callHXMod andromeda

echo -e "Configuring and copying Hexagonix static files... {\n" >> $LOG

cd Dist

echo "> Copying static configuration files (generated by configure.sh)..." >> $LOG

cd etc/

cp rc $BUILD_DIRECTORY/etc

echo " > rc successfully copied." >> $LOG

cp passwd $BUILD_DIRECTORY/etc

echo " > passwd successfully copied." >> $LOG

cp host $BUILD_DIRECTORY/etc

echo " > host configuration file successfully copied." >> $LOG

cp *.unx $BUILD_DIRECTORY/etc

echo " > *.unx files successfully copied." >> $LOG

cp base.ocl $BUILD_DIRECTORY/hexgnix.ocl
cp shrc $BUILD_DIRECTORY/etc

echo " > Hexagonix version files successfully copied." >> $LOG

cd ..

echo "> Copying Hexagonix utility manuals..." >> $LOG

cd man

cp *.man $BUILD_DIRECTORY

cd ..
cd ..

cd Fonts/

echo "> Checking for additional fonts to build..." >> $LOG

if [ -e aurora.asm ] ; then

echo -e "\nThere are graphic fonts to be built and copied... [\e[32mOk\e[0m]"
echo -e " > There are graphic fonts to be built and copied..." >> $LOG

./fonts.sh

cp *.fnt $BUILD_DIRECTORY
rm *.fnt

echo -ne "\nFonts copied [\e[32mOk\e[0m]\n"
echo " > Fonts copied." >> $LOG

else
echo -e "\nThere are no graphic fonts to build and copy... [\e[32mOk\e[0m]\n"
echo " > There are no graphic fonts to be built and copied..." >> $LOG

fi

# Let's also copy the header file to be able to develop on Hexagonix

cd ..

echo "> Copying core development libraries..." >> $LOG
echo -ne "\nCopying core development libraries..."

cd lib/fasm

cp hexagon.s $BUILD_DIRECTORY
cp console.s $BUILD_DIRECTORY
cp macros.s $BUILD_DIRECTORY

cd Estelar

cp estelar.s $BUILD_DIRECTORY

cd ..
cd ..

cd samples

cp * $BUILD_DIRECTORY

cd ..
cd ..

echo -e " [\e[32mOk\e[0m]\n"

echo -e "\n} Success configuring and copying Hexagonix configuration files.\n" >> $LOG
echo -e "----------------------------------------------------------------------\n" >> $LOG

callHXMod contribBuilder

}

# Imports

. $MOD_DIR/macros.hx 

# Constants

MOD_VER="0.3"

main $1